apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.11.0
        - --source=service
        - --source=ingress
        - --domain-filter=recipethesaurus.software # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=azure
        - --azure-resource-group=dns_rg        
        volumeMounts:
        - name: azure-dns-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-dns-config-file
        secret:
          secretName: azure-dns-config-file
