apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticconfig
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
   requests:
     storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fusionconfig
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
   requests:
    storage: 10Gi
