apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticdata
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: backofficestoreprem.privatelink.file.core.windows.net
    path: "/backofficestoreprem/elasticdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldata 
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: backofficestoreprem.privatelink.file.core.windows.net
    path: "/backofficestoreprem/mysqldata" 
