---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipethesaurus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipethesaurus
  template:
    metadata:
      labels:
        app: recipethesaurus 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
        - name: recipethesaurusregistrykey
      containers:      
        - name: recipethesaurus
          image: recipethesaurus.azurecr.io/recipethesaurus-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443 
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: recipethesaurus
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443 
  selector:
    app: recipethesaurus
  type: LoadBalancer
