name: build-image-ci

on:
  push:
    branches:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: recipethesaurus.azurecr.io
          username: recipethesaurus
          password: ${{ secrets.ACR }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Source_Code/RecipeThesaurus
          platforms: linux/amd64
          push: true
          file: ./Source_Code/RecipeThesaurus/RecipeThesaurus/Dockerfile
          tags: |
            recipethesaurus.azurecr.io/recipethesaurus-app:latest
