# .github/workflows/k8s-deploy.yml
on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: windows-latest
- name: Azure Kubernetes set context
  uses: Azure/aks-set-context@v3
- uses: azure/login@v1
  with:
     client-id: ${{ secrets.AZURE_CLIENT_ID }}
     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
- name: Kubectl tool installer
  uses: Azure/setup-kubectl@v3

- uses: azure/aks-set-context@v3
  with:
     resource-group: 'Backoffice'
     cluster-name: 'BackofficeAKSCluster'
  - name: Deploy to Kubernetes cluster
  uses: Azure/k8s-deploy@v4.9
- uses: Azure/k8s-deploy@v4
  with:
     resource-group: Backoffice 
     name: BackofficeAKSCluster
     action: deploy
     strategy: basic

     private-cluster: true
     manifests: |
     Source_Code/k8s/0_ingress_Controller.yaml
Source_Code/k8s/10_Frontend_DNS_Deployment.yaml
Source_Code/k8s/1_Backend_externalDNSconfig.yaml
Source_Code/k8s/2_Backend_Premium_PV.yaml
Source_Code/k8s/3_Backend_Standard_PV.yaml
Source_Code/k8s/4_Backend_Premium_PVC.yaml
Source_Code/k8s/5_Backend_Standard_PVC.yaml
Source_Code/k8s/6_Backend_SearchandDB.yaml
Source_Code/k8s/7_Backend_FusionAuth_App.yaml
Source_Code/k8s/8_Backend_nginx.yaml
Source_Code/k8s/9_Frontend_RecipeThesaurus_app.yaml
