# .github/workflows/k8s-deploy.yml
on:  
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: windows-latest
- name: Azure Kubernetes set context
  uses: Azure/aks-set-context@v3
- uses: azure/login@v1
  with:
     client-id: ${{ secrets.AZURE_CLIENT_ID }}
     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
- name: Kubectl tool installer
  uses: Azure/setup-kubectl@v3

- uses: azure/aks-set-context@v3
  with:
     resource-group: '<resource group name>'
     cluster-name: '<cluster name>'
  - name: Deploy to Kubernetes cluster
  uses: Azure/k8s-deploy@v4.9
- uses: Azure/k8s-deploy@v4
  with:
     resource-group: yourResourceGroup
     name: yourClusterName
     action: deploy
     strategy: basic

     private-cluster: true
     manifests: |
        manifests/azure-vote-backend-deployment.yaml
        manifests/azure-vote-backend-service.yaml
        manifests/azure-vote-frontend-deployment.yaml
        manifests/azure-vote-frontend-service.yaml
     images: |
        registry.azurecr.io/containername
