# This is a basic workflow to help you get started with Actions

name: Selenium Testing

on:
  push:
    branches:
      - 'feature/selenium'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get install wget && wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz
          tar -xf geckodriver-v0.32.2-linux64.tar.gz && sudo mv geckodriver /usr/local/bin
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test with selenium
        run: |
          python Source_Code/Selenium/main.py