# This is a basic workflow to help you get started with Actions

name: Selenium Testing

on:
  push:
    branches:
      - 'feature/selenium'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz
          tar -xf geckodriver-v0.32.2-linux64.tar.gz && sudo mv geckodriver /usr/local/bin
          export PROJECT_USERNAME=${{ secrets.PROJECT_USERNAME }}
          export PROJECT_PASSWORD=${{ secrets.PROJECT_PASSWORD }}
      - name: test with selenium
        run: |
          python Source_Code/Selenium/main.py